positive_quotes = [
    {"quote": "Le bonheur n’est pas quelque chose de pret a l’emploi. Il vient de vos propres actions.", "author": "Dalai Lama" },
    {"quote": "On ne change pas une equipe qui gagne.", "author": "Proverbe francais" },
    {"quote": "Vouloir, c’est pouvoir.", "author": "Proverbe francais" },
    {"quote": "Je pense, donc je suis.", "author": "Rene Descartes" },
    {"quote": "Fais toujours de ton mieux meme si personne ne regarde.", "author": "Proverbe japonais" },
    {"quote": "Il n’y a pas de raccourci pour aller la ou ca vaut la peine d’aller.", "author": "Beverly Sills" },
    {"quote": "La vie est un defi a relever, un bonheur a meriter, une aventure a tenter.", "author": "Mere Teresa" },
    {"quote": "La vie est un mystere qu'il faut vivre, et non un probleme a resoudre.", "author": "Gandhi" },
    {"quote": "Si vous aimez ce que vous faites, vous reussirez.", "author": "Albert Schweitzer" },
    {"quote": "La vie est un voyage, pas une destination.", "author": "Ralph Waldo Emerson" },
    {"quote": "Vous avez ete conecu pour faire des choses magiques.", "author": "" },
    {"quote": "L'espoir est un reve eveille.", "author": "Aristote" },
    {"quote": "Quand rien ne va bien, allez a gauche.", "author": "" },
    {"quote": "Concentrez-vous sur vos objectifs, pas sur les obstacles.", "author": "" },
    {"quote": "Transformer la douleur en pouvoir.", "author": "" },
    {"quote": "Il y a de la beaute dans la simplicite.", "author": "" },
    {"quote": "Transformer tes blessures en sagesse.", "author": "" },
    {"quote": "Votre meilleur professeur est votre dernière erreur.", "author": "" },
    {"quote": "C'est la volonte, pas la competence.", "author": "" },
    {"quote": "Un jour a la fois.", "author": "" },
    {"quote": "Tu comptes.", "author": "" },
    {"quote": "Ceci aussi devrait passer.", "author": "" },
    {"quote": "Ne jamais abandonner.", "author": "" },
    {"quote": "La positivite est le pouvoir.", "author": "" },
    {"quote": "Tu es incroyable.", "author": "" },
    {"quote": "Garde espoir.", "author": "" },
    {"quote": "Pense positivement.", "author": "" },
    {"quote": "Reste fort.", "author": "" },
    {"quote": "N'abandonne pas.", "author": "" },
    {"quote": "Brilles !", "author": "" },
    {"quote": "Je peux et je veux.", "author": "" },
    {"quote": "Les crayons casses colorent toujours.", "author": "" },
    {"quote": "Tu peux tout a fait faire ca.", "author": "" },
    {"quote": "Sois une voix. Pas un echo.", "author": "" },
    {"quote": "Aujourd'hui je choisis la joie.", "author": "" },
    {"quote": "Dis oui a de nouvelles aventures.", "author": "" },
    {"quote": "L'obstacle est le chemin.", "author": "" },
    {"quote": "Mourir avec des souvenirs, pas des reves.", "author": "" },
    {"quote": "C'est ok de ne pas etre ok maintenant.", "author": "" },
    {"quote": "Les petites choses font les grands jours.", "author": "" },
    {"quote": "Ta seule limite est ta croyance.", "author": "" },
    {"quote": "Fais confiance au timing de ta vie.", "author": "" },
    {"quote": "Ne te sens pas coupable de faire ce qui est le mieux pour toi.", "author": "" },
    {"quote": "Parfois plus tard devient jamais. Fais le maintenant.", "author": "" },
    {"quote": "Celui qui est courageux est libre.", "author": "Senèque" },
    {"quote": "Cherchez le chercheur.", "author": "Ramana Maharshi" },
    {"quote": "La positivite, c'est de trouver le bien meme dans de mauvaises conditions.", "author": "" },
    {"quote": "Chaque mur est une porte.", "author": "Ralph Waldo Emerson" },
    {"quote": "Aime la vie que tu vis. Vis la vie que tu aimes.", "author": "Bob Marley" },
    {"quote": "Le passe ne correspond pas au futur.", "author": "Tony Robbins" },
    {"quote": "Personne n'est parfait, c'est pourquoi les crayons ont des gommes", "author": "Wolfgang Riebe" },
    {"quote": "Le succès est l'enfant de l'audace.", "author": "Benjamin Disraeli" },
    {"quote": "Vous etes votre propre ame soeur.", "author": "Rupi Kaur" }
]
 
 